jmeno = input("Zadej své jméno: ")
print()
print("---------------------------")
print("Jméno: " + jmeno)
print("Obor: IT")
print("Zájmy: Editování videí")
print("---------------------------")
print()
